### ISSUE TITLE
Ability To Only Be In One Tournament At A Time

### ISSUE THREAD

**Issue by Mark-Ilkey** [brendanfly/wzclot#31]
Currently it is two or higher

**Comment by brendanfly** [comment]
Which tournament are you looking to have this for?

**Comment by Mark-Ilkey** [comment]
For now because it is. Just a small newish group of four of us playing one
game at a time
We have moved to a shared online spreadsheet which we can tailor in all
sorts of ways and have graphs and charts etc
Once we start to branch out a bit I will come back to your clot

Thanks
Mark

**Comment by brendanfly** [comment]
Right but which tournament do you want this in?

Swiss
Group Stage
Seeded
MTC
P/R League
Clan League
Random Round robin??

**Comment by Mark-Ilkey** [comment]
I was going to set up a round robin for the four of us but there was not
from memory an option of a single game
